AWSTemplateFormatVersion: '2010-09-09'
Description: API Gateway REST API with VPC Link for funds-btg

Resources:
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: funds-btg-api

  ProxyResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !GetAtt RestApi.RootResourceId
      PathPart: "{proxy+}"

  VpcLink:
    Type: AWS::ApiGateway::VpcLink
    Properties:
      Name: funds-btg-vpc-link
      TargetArns:
        - !ImportValue funds-btg-alb-arn

  ProxyMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !Ref ProxyResource
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: HTTP_PROXY
        IntegrationHttpMethod: ANY
        Uri: !Sub "http://${AlbDns}/{proxy}"
        ConnectionType: VPC_LINK
        ConnectionId: !Ref VpcLink

  RootMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !GetAtt RestApi.RootResourceId
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: HTTP_PROXY
        IntegrationHttpMethod: ANY
        Uri: !Sub "http://${AlbDns}"
        ConnectionType: VPC_LINK
        ConnectionId: !Ref VpcLink

  Deployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ProxyMethod
      - RootMethod
    Properties:
      RestApiId: !Ref RestApi
      StageName: prod

Outputs:
  ApiUrl:
    Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/prod"